name: Test

on:
  push:
    path:
      - 'cmd/**'
      - 'pkg/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.0
      - name: Test
        run: go test -v ./...